services:
  mongo:
    image: mongo:6.0.5-jammy
    container_name: mongodb
    hostname: mongodb
    restart: always
    pull_policy: always
    volumes:
      - ./mongo_data:/data/db
    networks:
      - graynet

  opensearch:
    image: opensearchproject/opensearch:2.2.0
    container_name: opensearch
    hostname: opensearch
    restart: always
    pull_policy: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    volumes:
      - ./log:/usr/share/opensearch/data
      - /etc/localtime:/etc/localtime:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200/tcp
    networks:
      - graynet

  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    hostname: graylog
    restart: always
    pull_policy: always
    environment:
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "sVqZPLzcHKvyijZUqFC8OANtnDQnIK6l"
      # echo -n password | shasum -a 256
      GRAYLOG_ROOT_PASSWORD_SHA2: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://128.66.0.2:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_TIMEZONE: "America/Caracas"
      TZ: "America/Caracas"
      GRAYLOG_TRANSPORT_EMAIL_PROTOCOL: "smtp"
      GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL: "http://128.66.0.2:9000/"
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: "outbound.mailhop.org"
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: "true"
      GRAYLOG_TRANSPORT_EMAIL_PORT: "587"
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "true"
      GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME: "xxxxx"
      GRAYLOG_TRANSPORT_EMAIL_AUTH_PASSWORD: "xxxxx"
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "true"
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
      GRAYLOG_TRANSPORT_FROM_EMAIL: "graylog@example.com"
      GRAYLOG_TRANSPORT_SUBJECT_PREFIX: "[graylog]"
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    volumes:
      - ./graylog.conf:/usr/share/graylog/config/graylog.conf:ro
      - ./graylog.conf:/usr/share/graylog/data/config/graylog.conf:ro
      - ./graylog_data:/usr/share/graylog/data
    networks:
      - graynet
    depends_on:
      opensearch:
        condition: "service_started"
      mongo:
        condition: "service_started"
    ports:
      - 9000:9000/tcp # Graylog web interface and REST API
      - 1514:1514/tcp # Syslog
      - 1514:1514/udp # Syslog
      - 12201:12201/tcp # GELF
      - 12201:12201/udp # GELF
      - 50001:50001/udp # prueba syslog udp

networks:
  graynet:
    driver: bridge
